---
version: "2"

linters:
  enable:
  - bodyclose
  - copyloopvar
  - importas
  - gocritic
  - govet
  - misspell
  - unconvert
  # - errorlint
  # - depguard
  # - gosec
  # - testifylint
  # - revive

formatters:
  enable:
  - gofmt
  - gofumpt
  - goimports
  - golines

issues:
  exclude-rules:
  - path: cmd/clone/clone.go
    linters:
    - errcheck
    - gocritic
  - path: cmd/*_test.go
    linters:
    - errcheck
    - gofumpt
