---
version: "2"

run:
  skip-files:
  - "^cmd/.*_test\\.go$"
  - cmd/status/status_test.go

linters:
  enable:
  - bodyclose
  - copyloopvar
  - importas
  - gocritic
  - govet
  - misspell
  - unconvert
  # - errorlint
  # - depguard
  # - gosec
  # - testifylint
  # - revive

formatters:
  enable:
  - gofmt
  - gofumpt
  - goimports
  - golines

linters-settings:
  errcheck:
    check-type-assertions: false

issues:
  exclude-use-default: false

exclude-rules:
- path: cmd/clone/clone.go
  linters:
  - errcheck
  - gocritic
